name: First workflow


on:
  push:
   branches:
    - main
jobs:
  examples-job:
    runs-on: ubuntu-latest


    steps:
      - name: Print a welcom message
        run: echo "Assalam to our first Github Actions Workfkows !!"

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: List repository files
        run: ls -la
